---
- hosts: Ubuntu
  gather_facts: no
  tasks:
    - name: copy tarball to host [eureka]
      copy:
        src: "./{{ services.eureka }}.tar"
        dest: '{{ deploy_path }}/{{ services.eureka }}.tar'

    - name: load container from tarball [eureka]
      docker_image:
        name: '{{ images_prefix }}/{{ services.eureka }}:latest'
        load_path: '{{ deploy_path }}/{{ services.eureka }}.tar'
        state: present
        source: load

    - name: copy tarball to host [weather]
      copy:
        src: "./{{ services.weather }}.tar"
        dest: '{{ deploy_path }}/{{ services.weather }}.tar'

    - name: load container from tarball [weather]
      docker_image:
        name: '{{ images_prefix }}/{{ services.weather }}:latest'
        load_path: '{{ deploy_path }}/{{ services.weather }}.tar'
        state: present
        source: load

    - name: copy tarball to host [currency]
      copy:
        src: "./{{ services.currency }}.tar"
        dest: '{{ deploy_path }}/{{ services.currency }}.tar'

    - name: load container from tarball [currency]
      docker_image:
        name: '{{ images_prefix }}/{{ services.currency }}:latest'
        load_path: '{{ deploy_path }}/{{ services.currency }}.tar'
        state: present
        source: load

    - name: copy tarball to host [prediction]
      copy:
        src: "./{{ services.prediction }}.tar"
        dest: '{{ deploy_path }}/{{ services.prediction }}.tar'

    - name: load container from tarball [prediction]
      docker_image:
        name: '{{ images_prefix }}/{{ services.prediction }}:latest'
        load_path: '{{ deploy_path }}/{{ services.prediction }}.tar'
        state: present
        source: load

    - name: copy docker compose file
      template:
        src: docker-compose.yml
        dest: "{{ deploy_path }}/docker-compose.yml"